(test) Add a basic e2e test for the interactive builder
openmrs/openmrs-esm-form-builder pull request #131
Opened 2023-05-23 22:14 UTC by denniskigen

## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR adds a basic e2e test for the interactive schema builder that simulates:

- Creating a form
- Adding a page to the form
- Adding a section to the form
- Adding a question to the form

Things not implemented:

- Selecting which answers to display from the selected concept
- Editing a question
- Some other scenarios I've not thought of yet

2023-05-24 13:16 UTC, anjula-sack requested changes

2023-05-24 18:35 UTC, denniskigen commented on e2e/specs/interactive-builder.spec.ts
> +  await page.getByRole("button", { name: /add page/i }).click();
Could you help me out with that?

2023-05-26 21:25 UTC, denniskigen commented on e2e/specs/interactive-builder.spec.ts
> +  await page.getByRole("button", { name: /add page/i }).click();
Done.

2023-06-03 10:27 UTC, anjula-sack approved these changes
Good job! @denniskigen

2023-06-03 10:27 UTC, merged