O3-1524: Implement form viewer component
openmrs/openmrs-esm-form-builder pull request #6
Opened 2022-09-14 18:10 UTC by kumuditha-udayanga

### Purpose
- Implement the form viewer component to OpenMRS form builder using the OHRI form engine.
- This component allows users to see a preview of the building form.

### Screenshots
![Screenshot 2022-09-14 at 11 36 44 PM](https://user-images.githubusercontent.com/27630091/190229681-b3893248-4d04-40a6-ae1c-1428ad5b2b52.png)

https://user-images.githubusercontent.com/27630091/190230022-35f01c9c-06e9-4da7-a4ad-bdfa65226aca.mov

2022-09-19 12:29 UTC, samuelmale requested changes
Almost there, just one minor comment.

2022-09-19 12:29 UTC, samuelmale commented on src/components/form-editor/form-renderer/form-renderer.tsx
> +  const patientUUID = "b280078a-c0ce-443b-9997-3c66c63ec2f8";
This should be driven through a config, what happens if I ran this app against an OpenMRS instance without a patient with uuid: `"b280078a-c0ce-443b-9997-3c66c63ec2f8"`?

2022-09-19 18:44 UTC, kumuditha-udayanga commented
Thank you for the review @samuelmale, the requested change is made

2022-09-20 06:08 UTC, samuelmale approved these changes
LGTM

2022-09-20 06:08 UTC, merged